// Code generated by "stringer -type=play"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[rock-0]
	_ = x[scissors-1]
	_ = x[paper-2]
}

const _play_name = "rockscissorspaper"

var _play_index = [...]uint8{0, 4, 12, 17}

func (i play) String() string {
	if i < 0 || i >= play(len(_play_index)-1) {
		return "play(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _play_name[_play_index[i]:_play_index[i+1]]
}
